import crypto from "crypto";
import fs from "fs";
import os from "os";
import path from "path";
import { v4 } from "uuid";
import { multiplayer, MultiplayerData } from "nova_ecs/plugins/multiplayer_plugin";
import { MockCommunicator } from "nova_ecs/plugins/mock_communicator";
import { GameDataAggregator } from "../server/parsing/game_data_aggregator.js";
import { FilesystemData } from "../server/parsing/filesystem_data.js";
import { NovaParse } from "novaparse";
import { ControlBitResolver } from "../nova_plugin/ncb/index.js";
import { completeEntity } from "../nova_plugin/spawn/index.js";
import { makeShip } from "../nova_plugin/ship/index.js";
import { makeSystem } from "../nova_plugin/make_system.js";
import { PlayerShipSelector } from "../nova_plugin/player/index.js";
import { SimulationBridgeClient } from "./simulation_bridge_client.js";
import { SimulationBridgeHost } from "./simulation_bridge_host.js";
import { SerializerResource } from "nova_ecs/plugins/serializer_plugin";
import { novaDataInstalled, requireNovaData } from "../test_support/nova_data_gate.js";
import { fileURLToPath } from "url";

/**
 * The nearest directory at or above `from` holding a package.json.
 * This module runs from dist/src/communication/ (jasmine, the built
 * tree) or src/communication/ (an editor's ts runner), so the package
 * root is found by walking up rather than by counting levels.
 */
function findPackageRoot(from: string): string {
    let dir = from;
    for (; ;) {
        if (fs.existsSync(path.join(dir, "package.json"))) {
            return dir;
        }
        const parent = path.dirname(dir);
        if (parent === dir) {
            throw new Error(`No package.json at or above ${from}`);
        }
        dir = parent;
    }
}

/**
 * packages/nova, anchored to THIS module rather than to process.cwd(),
 * so the fixtures (the synthetic set under test_fixtures, Nova_Data,
 * objects/, settings/) resolve from any cwd: a jasmine run from the repo
 * root, a scratch script, a debugger. Under packages/nova's jasmine.json
 * the two agree, so nothing changes for the suite; the data gate keeps
 * its own cwd default and is handed this root explicitly.
 */
const packageRoot = findPackageRoot(path.dirname(fileURLToPath(import.meta.url)));

let gameDataPromise: Promise<GameDataAggregator> | undefined;

/**
 * THE TWO DATA SETS A SPEC CAN RUN ON
 *
 * `getIntegrationGameData()` parses the real, copyrighted Nova Files out
 * of Nova_Data: slow (tens of seconds cold), machine-dependent, and absent
 * on CI, where every spec that asks for it pends. `getSyntheticGameData()`
 * parses the SYNTHETIC set checked in at test_fixtures/synthetic — a
 * small, original scenario generated by novaparse's src/synthetic
 * (four systems, ten stellars, six ships, fourteen weapons, twenty-nine
 * outfits, four governments, NPC tables, persons, specialised cargo,
 * missions, ranks, a default pilot, and the pictures the display asks
 * for at the stock dialog sizes; see universe.ts there for the whole
 * map). It loads in well under a second through the very same
 * NovaParse + GameDataAggregator path, so what a converted spec exercises
 * is the real parser and the real game rules, on data the repo owns.
 *
 * CONVERSION RECIPE (a spec that needs no stock-specific content):
 *
 *  1. Swap `getIntegrationGameData` for `getSyntheticGameData` (and pass
 *     `getSyntheticGameData()` to `makeSimulationBridgeHarness` /
 *     `makeDeterminismWorld`, which take the data set as a parameter).
 *  2. Replace stock ids with the scenario's, by name, from
 *     `SYNTHETIC` in novaparse/synthetic/universe: `SYNTHETIC.ships.skiff`,
 *     `SYNTHETIC.planets.port`, `SYNTHETIC.systems.thessaly`... The
 *     scenario loads under the base "nova" prefix, and its port, default
 *     pilot and first system are all nova:128, so a spec that only says
 *     'nova:128' for "the starting planet / pilot / system" usually
 *     needs no edit at all. The sorted-first system is Thessaly Reach and
 *     the sorted-first ship the Wren Skiff (a plain inertial hull with
 *     one blaster), which is what the "pick the first id" fixtures get.
 *  3. Drop the `requireNovaData` / `novaDataInstalled` gating: the
 *     synthetic set is always present.
 *  4. Keep on the integration set anything that pins STOCK content
 *     (a named Federation ship's stats, the stacked Sols, the hypergate
 *     network's 16 dead gates): that is what those specs are for.
 *
 * What the scenario has for the common shapes: a jump (Thessaly links
 * Kestrel Drift and Ossory Shoal), a landing at a full-service port
 * (Port Amberline, nova:128: shipyard, outfitter, bar, trade centre,
 * mission computer), an uninhabited landable moon, a second inhabited
 * world in the starting system with MinStatus 0 whose bribable govt is
 * Meridian's ally (Coldharbour), an unlandable gas giant, a linked
 * hypergate pair (Kestrel Gate / Vael Gate) with an ordinary rock beside
 * one gate, a link-less wormhole pair (Ossory Rift / Vael Rift), a
 * station that needs a legal record of 20 with the raiders, NPC traffic
 * in every system (traders and patrol in Thessaly; raiders and a raider
 * fleet in Kestrel), persons in three of the four systems (one bound to
 * a system, one anywhere, one to a govt range, one hailing with a
 * rescue offer, one derelict offering a job on boarding), two jünk
 * commodities, a missile with ammo and a point defence to shoot it
 * down, a beam, a turret, a fighter bay on the Heron Warden, a cloak
 * sold only at the secret station, three hulls no traffic table carries
 * (a cloaked and jammed raider, a 10,000-ton hauler, a 10-ton drone)
 * with the rule weapons (beam turret, no-reload beam, blind-spot
 * turrets, front-quadrant gun, a second bay) and the flagged outfits
 * (Require/Contribute, persistent, cantSell, removeAfterPurchase,
 * OnPurchase Hxxx, BuyRandom 0), a mission-computer job whose OnAccept
 * sets b100, a bar job, a bounty, a ship-offered rescue, a boarding
 * salvage, and jobs at the outfitter, shipyard and trade centre.
 */
export async function getSyntheticGameData(): Promise<GameDataAggregator> {
    if (!syntheticGameDataPromise) {
        syntheticGameDataPromise = Promise.resolve(makeSyntheticGameData());
    }
    return syntheticGameDataPromise;
}

let syntheticGameDataPromise: Promise<GameDataAggregator> | undefined;

/** Where the checked-in synthetic set lives (a Nova_Data-shaped root). */
export const SYNTHETIC_DATA_ROOT = path.join(packageRoot, "test_fixtures", "synthetic");

/**
 * A FRESH aggregator over the synthetic set, with a cold cache of its own
 * (see makeIntegrationGameData for when that matters). Unlike the
 * integration parser this one is NOT silenced: the synthetic set
 * references nothing it does not carry, so a not-found report here is a
 * real defect in the scenario or the parser, and should be seen.
 */
export function makeSyntheticGameData(): GameDataAggregator {
    const novaParse = new NovaParse(SYNTHETIC_DATA_ROOT, false,
        { novaFiles: "Nova Files", novaPlugins: "Plug-ins" });
    const aggregator = new GameDataAggregator([
        new FilesystemData(path.join(packageRoot, "objects")),
        novaParse,
    ], () => { });
    aggregator.getSettings =
        async (file: string) => JSON.parse(await fs.promises.readFile(
            path.join(packageRoot, 'settings', file), 'utf8'));
    return aggregator;
}

export async function getIntegrationGameData() {
    // No Nova_Data (CI, a fresh clone): the calling spec is marked pending
    // rather than failing on the parser's rejection. See nova_data_gate.ts
    // for the beforeAll caveat.
    requireNovaData(packageRoot);
    if (!gameDataPromise) {
        gameDataPromise = Promise.resolve(makeIntegrationGameData());
    }
    return gameDataPromise;
}

/**
 * A FRESH aggregator over the base data, with a cold cache of its own.
 * getIntegrationGameData memoizes one per process, so every world in a
 * spec run shares its cache — which is exactly what a "this world never
 * staged that id" spec must not share. Loading is lazy per id, so a
 * second aggregator costs only what the spec then loads through it.
 */
export function makeIntegrationGameData(): GameDataAggregator {
    // Base "Nova Files" data ONLY (novaPlugins: null). Tests must not
    // depend on which plug-ins happen to be installed in the developer's
    // Nova_Data/Plug-ins directory — otherwise ids, ship/system/outfit
    // stats and even sorted-first ids change from machine to machine.
    // The dev server (server.ts / nova_parse_worker.ts) still loads
    // plug-ins as usual; only tests opt out.
    const novaParse = new NovaParse(path.join(packageRoot, "Nova_Data"), false,
        { novaFiles: "Nova Files", novaPlugins: null });
    novaParse.resourceNotFoundFunction = () => { };
    const aggregator = new GameDataAggregator([
        new FilesystemData(path.join(packageRoot, "objects")),
        novaParse,
    ], () => { });
    // The browser fetches settings over HTTP; in node, read them
    // from disk so worlds can build with the 'worker' platform
    // (which includes the control systems).
    aggregator.getSettings =
        async (file: string) => JSON.parse(await fs.promises.readFile(
            path.join(packageRoot, 'settings', file), 'utf8'));
    return aggregator;
}

const pluginDataPromises = new Map<string, Promise<GameDataAggregator | undefined>>();

/**
 * Base "Nova Files" data PLUS exactly one named plug-in directory from
 * Nova_Data/Plug-ins — for specs that pin behaviour against real
 * third-party scenario data (the compatibility rules in nova_plugin/ncb/ncb.ts,
 * say). Resolves to undefined when that plug-in is not installed, so such a
 * spec can skip itself instead of failing on a machine (or CI) without it.
 *
 * Only the ONE plug-in is loaded, and it is loaded through a scratch
 * Nova_Data root of symlinks rather than the real Plug-ins directory. That
 * matters for the same reason getIntegrationGameData loads no plug-ins at
 * all: whatever else a developer happens to have installed must not shift
 * ids or stats underneath the spec. Symlinking (never copying) also keeps
 * the canonical data read-only and preserves the macOS resource forks the
 * parser reads.
 *
 * The plug-in's id prefix is its DIRECTORY name, which is why the directory
 * itself is the thing linked: pointing novaPlugins at it directly would
 * give each file inside its own prefix instead.
 */
export async function getPluginGameData(
    pluginDirectory: string | string[]):
    Promise<GameDataAggregator | undefined> {
    // Several plug-ins may be loaded together (for the specs about how
    // plug-ins interact, e.g. Require/Contribute flag namespacing). The
    // set is what matters, not the order given: NovaParse loads plug-ins
    // in a sorted order of its own regardless.
    const directories = [...new Set(
        typeof pluginDirectory === "string"
            ? [pluginDirectory] : pluginDirectory)].sort();
    const key = directories.join("+");
    let promise = pluginDataPromises.get(key);
    if (!promise) {
        promise = buildPluginGameData(directories);
        pluginDataPromises.set(key, promise);
    }
    return promise;
}

/**
 * The PHYSICAL control bit that plug-in `namespace`'s raw bit `bit` was
 * given under `gameData`'s plug-in set (see
 * nova_plugin/ncb/control_bit_namespaces.ts). Specs that drive a plug-in's
 * gates by its own bit numbers (`b9009` in Extra Outfits, say) must go
 * through this, because NovaParse renumbers plug-in-private bits.
 */
export async function pluginControlBit(gameData: GameDataAggregator,
    namespace: string, bit: number): Promise<number> {
    const resolver = new ControlBitResolver(await gameData.controlBitNamespaces);
    const physical = resolver.physicalBit([namespace, bit]);
    if (physical === undefined) {
        throw new Error(`Plug-in '${namespace}' has no control bit b${bit}`);
    }
    return physical;
}

async function buildPluginGameData(pluginDirectories: string[]):
    Promise<GameDataAggregator | undefined> {
    const novaParse = makePluginNovaParse(pluginDirectories);
    if (!novaParse) {
        return undefined;
    }
    return new GameDataAggregator([
        new FilesystemData(path.join(packageRoot, "objects")),
        novaParse,
    ], () => { });
}

/**
 * A FRESH, uncached NovaParse over base data plus the named plug-in
 * directories (see getPluginGameData for the scratch-root arrangement),
 * or undefined if any of them is not installed. For specs that need to
 * parse the same plug-in set more than once — the determinism of the
 * Require/Contribute flag namespacing, say. Prefer getPluginGameData
 * (cached, wrapped in the aggregator) for everything else.
 */
export function makePluginNovaParse(pluginDirectories: string[]):
    NovaParse | undefined {
    const novaData = path.join(packageRoot, "Nova_Data");
    const pluginPaths = pluginDirectories.map(
        dir => path.join(novaData, "Plug-ins", dir));
    // The base data is checked too: with an EMPTY plug-in list the
    // every() below is vacuously true, and the spec would otherwise reach
    // the parser's rejection instead of skipping.
    if (!novaDataInstalled(packageRoot)
        || !pluginPaths.every(p => fs.existsSync(p))) {
        return undefined;
    }
    // A fixed scratch root, reused across runs rather than a fresh mkdtemp
    // each time, so repeated test runs don't litter the temp directory.
    // Keyed by this checkout too: worktrees run these specs concurrently,
    // and a root shared between them would flip the links under a
    // running parse (and go stale when the worktree that made it is
    // removed).
    const checkoutKey = crypto.createHash("sha1").update(packageRoot)
        .digest("hex").slice(0, 8);
    const root = path.join(os.tmpdir(),
        `novajs-plugin-fixture-${checkoutKey}-${pluginDirectories.join("+")}`);
    fs.mkdirSync(path.join(root, "Plug-ins"), { recursive: true });
    linkOnce(path.join(novaData, "Nova Files"), path.join(root, "Nova Files"));
    for (let i = 0; i < pluginDirectories.length; i++) {
        linkOnce(pluginPaths[i],
            path.join(root, "Plug-ins", pluginDirectories[i]));
    }

    const novaParse = new NovaParse(root, false,
        { novaFiles: "Nova Files", novaPlugins: "Plug-ins" });
    novaParse.resourceNotFoundFunction = () => { };
    // The one-time flag namespacing diagnostics are for people loading a
    // real Plug-ins folder, not for the test log.
    novaParse.flagNamespaceWarn = () => { };
    novaParse.controlBitNamespaceWarn = () => { };
    return novaParse;
}

function linkOnce(target: string, link: string) {
    // lstat, not existsSync: a DANGLING link (its worktree was removed)
    // reports as absent and the symlink then fails with EEXIST. Re-point
    // anything that is not already the wanted link.
    try {
        if (fs.readlinkSync(link) === target) {
            return;
        }
        fs.unlinkSync(link);
    } catch (e) {
        if ((e as NodeJS.ErrnoException).code !== "ENOENT") {
            throw e;
        }
    }
    fs.symlinkSync(target, link);
}

/**
 * A controlled battlefield: the sorted-first system with the sorted-first
 * ship in it, bridged. Runs on the integration data unless another set
 * is given (`makeSimulationBridgeHarness(getSyntheticGameData())`).
 */
export async function makeSimulationBridgeHarness(
    gameDataSource: Promise<GameDataAggregator> = getIntegrationGameData()) {
    const gameData = await gameDataSource;
    const ids = await gameData.ids;
    const systemId = [...ids.System].sort()[0];
    const shipId = [...ids.Ship].sort()[0];

    if (!systemId) {
        throw new Error("Expected at least one system id");
    }
    if (!shipId) {
        throw new Error("Expected at least one ship id");
    }

    // No NPC traffic: this harness is a controlled battlefield. With
    // base data only, the sorted-first ids are the stock sÿst nova:1124
    // (Procyon, AvgShips 1) and shïp nova:128 (the Shuttle); ambient
    // spawns would still make the battlefield nondeterministic to
    // reason about, so they stay off.
    const world = await makeSystem(systemId, gameData, undefined,
        { npcs: false });
    const communicator = new MockCommunicator("server");
    await world.addPlugin(multiplayer(communicator));

    const shipData = await gameData.data.Ship.get(shipId);
    const ship = makeShip(shipData);
    const shipUuid = v4();
    ship.components.set(MultiplayerData, { owner: "server" });
    ship.components.set(PlayerShipSelector, undefined);
    await completeEntity(world, ship);
    world.entities.set(shipUuid, ship);

    for (let i = 0; i < 10; i++) {
        world.step();
    }

    const serializer = world.resources.get(SerializerResource);
    if (!serializer) {
        throw new Error("Expected simulation serializer resource");
    }

    const host = new SimulationBridgeHost(world, gameData);
    const client = new SimulationBridgeClient(host, serializer);

    return {
        client,
        gameData,
        shipId,
        shipUuid,
        systemId,
        world,
    };
}
