steps:
  - name: gcr.io/cloud-marketplace-containers/google/bazel:3.5.0
    id: unittest
    args: ['test', '--google_default_credentials', '--remote_http_cache=https://storage.googleapis.com/bazel-remote-cache-novajs', '...']

timeout: 900s
